version: "3.7"
services:
  db:
    build: ./docker/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - rails_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
  web:
    build: ./docker/web
    container_name: rails
    privileged: true
    command: /sbin/init
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpass
volumes:
    rails_db_data: {}      